### ISSUE TITLE
Elaboration: Implementering: Persitences

### ISSUE THREAD

**Issue by kvartborg** [kvartborg/2-semesterprojekt#101]

**Comment by MadsDueKristensen** [comment]
Tænker at det ville være godt at uddybe hvordan query() methoden på database-klassen virker og hvorfor der bliver brugt et interface Handler.

Ved ikke om det hører til her med vi bør nok nævne Mapperen, og den betydning i programmet. Og eventuelt uddybe hvordan den virker.

**Comment by grammeaway** [comment]
I'll try to add some, men er faktisk ikke selv helt sikker på hvordan query() fungerer 0__0 

Helt enig, men tror ikke det er her den hører til - måske vi skal have nogle afsnit med ting som mapperen og singleton-brugen forklaret?

**Comment by grammeaway** [comment]
Derudover frygter jeg lidt at afsnittet bliver for langt
