### ISSUE TITLE
Metode og planlægning

### ISSUE THREAD

**Issue by kvartborg** [kvartborg/2-semesterprojekt#94]

**Comment by grammeaway** [comment]
@GGkarma 
Review: 
Quality shit overall, dejligt velskrevet 🔥 Faldt over nogle få uregelmæssigheder:

I afsnittet om Scrum har jeg rettet beskrivelsen af Scrum masterens rolle. Den gav før udtryk for at crum masteren var leder af teamet, hvilket ikke er tilfældet. Han er derimod leder af Scrum processen, og står for at sørge for at den bliver overholdt 😃 (somebody correct me if I'm wrong here)
I Scrum afsnittet nævner du et par gange at projektet har 4 overordnede faser, hvilket jeg ikke rigtig ved om er rigtigt eller forkert.. I UP er der ganske rigtigt 4, men har vi ikek kun været igennem inception og elaboration? Måske vi lgie vender den med gruppen 0__0 

Første to afsnit af Planlægning virker selvmodsigende. Først beskrives vores 1-uges sprinter som for korte (korrekt), men derefter beskrives 2-ugers sprints som havende en kortere itterationscyklus, hvilket vel egentlig er forkert, da der kommer færre itterationer ud fra længere sprints.

GitHub boardet skal måske bare i interne bilag og så refereres til? Måske for meget plads det tager i forhold til hvor vigtigt det er - eventuelt høre gruppen?
