### ISSUE TITLE
Elaboration: Analyse

### ISSUE THREAD

**Issue by kvartborg** [kvartborg/2-semesterprojekt#96]

**Comment by grammeaway** [comment]
@MadsDueKristensen 
Review: 
Looks good, har rettet lidt grammatik og slåfejl rundt omkring, så læs det lige igennem og tjek om alting stadigvæk formidler de pointer det skal.
I tabel 8, kontrakten for login() er der ved et af underpunkterne følgende formulering: "En brugere må password og username passer med oplysninger i systemet."  - var ikke lige sikker på hvad der burde stå, måske du selv lige vil rette den? 
Under postconditions i samme kontrakt skriver du: "Der er oprettet en instans af bruger, der bliver gemt i memory".  Correct me if I'm wrong, men den opretter da ikke en bruger, eller hvad? Tjekker om det stemmer med de eksisterende brugere i databasen? 

Jeg har rettet "Arkitektur diagram" til "arkitektonisk interaktionsdiagram", som en helgardering. Kunne godt mistænke at "arkitektur diagram" dækkede over en anden diagramtype. "Arkitektonisk interaktionsdiagram" var derudover også navnet på diagrammet i øvelserne 😄 

Det eneste der måske kunne være mere om er hvad der i UP forstås ved ansvar. Husker det som at Lone har snakket en del om det, tror måske der er noget om de ti hendes eget dokument
